### ISSUE TITLE
NPE "Thread local SslConfig has not been set" with Java 11

### ISSUE THREAD

**Issue by nilius** [vt-middleware/ldaptive#159] opened 2019-11-07 15:09 UTC
We have just updated our application from Java 8 to Java 11.

We are now getting the following NullPointerException:
`Caused by: java.lang.NullPointerException: Thread local SslConfig has not been set
	at org.ldaptive.ssl.ThreadLocalTLSSocketFactory.getDefault(ThreadLocalTLSSocketFactory.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:278)
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:216)
	... 38 common frames omitted`
When we change back to Java 8, everything is OK.

We are using org.ldaptive.ldaptive in version "1.2.4" on linux, if you need more information let us know.

Is this a known bug? I could not find anything in the backlog. 
I found some related information and thoughts in this thread (we are NOT using shibboleth identity Provider, though)
https://issues.shibboleth.net/jira/browse/IDP-1357?attachmentSortBy=dateTime

Best regards

Fabian Nilius

**Comment by dfish3r** [comment] 2019-11-10 01:56
This is a known bug, it's caused by this bug in the JDK:
https://bugs.openjdk.java.net/browse/JDK-8217606

The best work around right now for Java 11 is to use the UnboundID provider.

**Comment by dfish3r** [comment] 2020-08-12 20:47
So there are now three more potential solutions for this:
1) Upgrade to ldaptive v2
2) Use version 1.3 which defaults to the UnboundID provider
3) Upgrade to Java 14, which should contain the fix for this bug

**Closed by dfish3r** 2020-08-12 20:47 UTC
