### ISSUE TITLE
ClassNotFoundException: org.ldaptive.ssl.ThreadLocalTLSSocketFactory with Java 9

### ISSUE THREAD

**Issue by floragunn** [vt-middleware/ldaptive#134] opened 2018-03-29 10:22 UTC
Usage of ldaptive with Java 9 leads to **ClassNotFoundException: org.ldaptive.ssl.ThreadLocalTLSSocketFactory**

<pre>
[org.ldaptive.OperationException@513999578::resultCode=PROTOCOL_ERROR, matchedDn=null, responseControls=null, referralURLs=null, messageId=-1,
message=javax.naming.CommunicationException: ldap.example.com:636 [Root exception is
 java.lang.ClassNotFoundException: org.ldaptive.ssl.ThreadLocalTLSSocketFactory], 
providerException=javax.naming.CommunicationException: ldap.example.com:636 [Root
 exception is java.lang.ClassNotFoundException: 
org.ldaptive.ssl.ThreadLocalTLSSocketFactory]]
</pre>

Same code runs perfectly fine with Java 8.

What is the roadmap for ldaptive regarding to Java 9/10/11 ... readiness?

**Comment by dfish3r** [comment] 2018-03-29 13:53
My integration tests ran with a little tweaking on
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

**Comment by floragunncom** [comment] 2018-03-29 14:04
Version 1.2.3. 
Need to isolate a reproducer because we have security manager enabled and therefore wrap thing in AccessController.doPrivileged(), perhaps this is causing some classloader hassle.

The code where this happens is here https://github.com/floragunncom/search-guard-enterprise-modules/blob/master/src/main/java/com/floragunn/dlic/auth/ldap/backend/LDAPAuthorizationBackend.java#L112 but its not reproducible yet from the unittests.

Maybe related to https://github.com/vt-middleware/ldaptive/issues/99

**Comment by floragunncom** [comment] 2018-04-02 11:17
Not yet a reproducer (working on that) but at least a stracktrace:

<pre>
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.getConnection0(LDAPAuthorizationBackend.java:215) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.access$000(LDAPAuthorizationBackend.java:79) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend$1.run(LDAPAuthorizationBackend.java:114) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend$1.run(LDAPAuthorizationBackend.java:111) ~[?:?]
 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.getConnection(LDAPAuthorizationBackend.java:111) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.fillRoles(LDAPAuthorizationBackend.java:383) ~[?:?]
 	... 73 more
 Caused by: org.ldaptive.OperationException: javax.naming.CommunicationException: ldap.example.com:636 [Root exception is java.lang.ClassNotFoundException: org.ldaptive.ssl.ThreadLocalTLSSocketFactory]
 	at org.ldaptive.provider.ProviderUtils.throwOperationException(ProviderUtils.java:50) ~[?:?]
 	at org.ldaptive.provider.jndi.JndiConnection.processNamingException(JndiConnection.java:619) ~[?:?]
 	at org.ldaptive.provider.jndi.JndiConnection.anonymousBind(JndiConnection.java:232) ~[?:?]
 	at org.ldaptive.provider.jndi.JndiConnection.bind(JndiConnection.java:201) ~[?:?]
 	at org.ldaptive.DefaultConnectionFactory$DefaultConnection.open(DefaultConnectionFactory.java:295) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.getConnection0(LDAPAuthorizationBackend.java:195) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.access$000(LDAPAuthorizationBackend.java:79) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend$1.run(LDAPAuthorizationBackend.java:114) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend$1.run(LDAPAuthorizationBackend.java:111) ~[?:?]
 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.getConnection(LDAPAuthorizationBackend.java:111) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.fillRoles(LDAPAuthorizationBackend.java:383) ~[?:?]
 	... 73 more
 Caused by: javax.naming.CommunicationException: ldap.example.com:636
 	at com.sun.jndi.ldap.Connection.<init>(Connection.java:223) ~[?:?]
 	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137) ~[?:?]
 	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616) ~[?:?]
 	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2752) ~[?:?]
 	at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2702) ~[?:?]
 	at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2676) ~[?:?]
 	at com.sun.jndi.ldap.LdapCtx.reconnect(LdapCtx.java:2672) ~[?:?]
 	at javax.naming.ldap.InitialLdapContext.reconnect(InitialLdapContext.java:193) ~[?:?]
 	at org.ldaptive.provider.jndi.JndiConnection.anonymousBind(JndiConnection.java:226) ~[?:?]
 	at org.ldaptive.provider.jndi.JndiConnection.bind(JndiConnection.java:201) ~[?:?]
 	at org.ldaptive.DefaultConnectionFactory$DefaultConnection.open(DefaultConnectionFactory.java:295) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.getConnection0(LDAPAuthorizationBackend.java:195) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.access$000(LDAPAuthorizationBackend.java:79) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend$1.run(LDAPAuthorizationBackend.java:114) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend$1.run(LDAPAuthorizationBackend.java:111) ~[?:?]
 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.getConnection(LDAPAuthorizationBackend.java:111) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.fillRoles(LDAPAuthorizationBackend.java:383) ~[?:?]
 	... 73 more
 Caused by: java.lang.ClassNotFoundException: org.ldaptive.ssl.ThreadLocalTLSSocketFactory
 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[?:?]
 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185) ~[?:?]
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
 	at java.lang.Class.forName0(Native Method) ~[?:?]
 	at java.lang.Class.forName(Class.java:375) ~[?:?]
 	at com.sun.jndi.ldap.VersionHelper.loadClass(VersionHelper.java:76) ~[?:?]
 	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:261) ~[?:?]
 	at com.sun.jndi.ldap.Connection.<init>(Connection.java:202) ~[?:?]
 	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137) ~[?:?]
 	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616) ~[?:?]
 	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2752) ~[?:?]
 	at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2702) ~[?:?]
 	at com.sun.jndi.ldap.LdapCtx.ensureOpen(LdapCtx.java:2676) ~[?:?]
 	at com.sun.jndi.ldap.LdapCtx.reconnect(LdapCtx.java:2672) ~[?:?]
 	at javax.naming.ldap.InitialLdapContext.reconnect(InitialLdapContext.java:193) ~[?:?]
 	at org.ldaptive.provider.jndi.JndiConnection.anonymousBind(JndiConnection.java:226) ~[?:?]
 	at org.ldaptive.provider.jndi.JndiConnection.bind(JndiConnection.java:201) ~[?:?]
 	at org.ldaptive.DefaultConnectionFactory$DefaultConnection.open(DefaultConnectionFactory.java:295) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.getConnection0(LDAPAuthorizationBackend.java:195) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.access$000(LDAPAuthorizationBackend.java:79) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend$1.run(LDAPAuthorizationBackend.java:114) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend$1.run(LDAPAuthorizationBackend.java:111) ~[?:?]
 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.getConnection(LDAPAuthorizationBackend.java:111) ~[?:?]
 	at com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend.fillRoles(LDAPAuthorizationBackend.java:383) ~[?:?]
 	... 73 more
</pre>

so the problem seems to be here

<pre>
at org.ldaptive.provider.jndi.JndiConnection.anonymousBind(JndiConnection.java:226) ~[?:?]
 	at org.ldaptive.provider.jndi.JndiConnection.bind(JndiConnection.java:201) ~[?:?]
 	at org.ldaptive.DefaultConnectionFactory$DefaultConnection.open(DefaultConnectionFactory.java:295) ~[?:?]
</pre>

**Comment by dfish3r** [comment] 2020-08-12 20:54
With the release of v2, closing out v1 issues.

**Closed by dfish3r** 2020-08-12 20:54 UTC
