### ISSUE TITLE
BeanGenerator  mailRecipient object class 50ns-mail problem

### ISSUE THREAD

**Issue by sysmat** [vt-middleware/ldaptive#32] opened 2015-04-28 07:52 UTC
ldaptive-beans:version = 1.0.6

Exception:
Exception in thread "main" java.lang.IllegalArgumentException: Could not transcode object class
	at org.ldaptive.schema.io.ObjectClassValueTranscoder.decodeStringValue(ObjectClassValueTranscoder.java:37)
	at org.ldaptive.schema.io.ObjectClassValueTranscoder.decodeStringValue(ObjectClassValueTranscoder.java:25)
	at org.ldaptive.LdapAttribute.getValues(LdapAttribute.java:283)
	at org.ldaptive.schema.SchemaFactory.createSchema(SchemaFactory.java:219)
	at org.ldaptive.schema.SchemaFactory.createSchema(SchemaFactory.java:120)
	at test.LdaptiveBeanGenerator.main(LdaptiveBeanGenerator.java:49)
Caused by: java.text.ParseException: Invalid object class definition: ( 2.16.840.1.113730.3.2.3 NAME 'mailRecipient' DESC '' SUP top AUXILIARY MAY ( cn $ mail $ mailAlternateAddress $ mailHost $ mailRoutingAddress $ mailAccessDomain $ mailAutoReplyMode $ mailAutoReplyText $ mailDeliveryOption $ mailForwardingAddress $ mailMessageStore $ mailProgramDeliveryInfo $ mailQuota $ multiLineDescription $ uid $ userPassword ) X-ORIGIN 'Netscape Messaging Server 4.x' )

The ObjectClass is part of https://github.com/leto/389-ds/blob/master/ldap/schema/50ns-mail.ldif 

Regards, Tomaz

**Comment by dfish3r** [comment] 2015-04-28 14:05
This is a duplicate of #31.
Please checkout the 1.1.0-SNAPSHOT and reopen that issue if necessary.

**Closed** 2015-04-28 14:05 UTC

**Comment by sysmat** [comment] 2015-04-29 06:01
Dne 28.4.2015 ob 16:05 je Daniel Fisher zapisal(a):
>
> This is a duplicate of #31 
> <https://github.com/vt-middleware/ldaptive/issues/31>.
> Please checkout the 1.1.0-SNAPSHOT and reopen that issue if necessary.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/vt-middleware/ldaptive/issues/32#issuecomment-97074759>.
>
I downloaded from git(1.1.0-SNAPSHOT), run maven package and have test 
failure(CORE).

Regards, Tomaz

**Comment by sysmat** [comment] 2015-04-29 08:14
Dne 29.4.2015 ob 8:01 je Tomaz Majerhold zapisal(a):
> Dne 28.4.2015 ob 16:05 je Daniel Fisher zapisal(a):
>>
>> This is a duplicate of #31 
>> <https://github.com/vt-middleware/ldaptive/issues/31>.
>> Please checkout the 1.1.0-SNAPSHOT and reopen that issue if necessary.
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/vt-middleware/ldaptive/issues/32#issuecomment-97074759>.
>>
> I downloaded from git(1.1.0-SNAPSHOT), run maven package and have test 
> failure(CORE).
>
> Regards, Tomaz
I build on a top of project, on  beans build with test and it is ok.

Regards, Tomaz
