### ISSUE TITLE
JNDIProvider leaks connections when Java >=9

### ISSUE THREAD

**Issue by floragunn** [vt-middleware/ldaptive#148] opened 2019-07-20 22:50 UTC
This is due to https://bugs.openjdk.java.net/browse/JDK-8217606 introduced with java 9.

Main issue that `LdapContext.reconnect()` now creates a physical connection.
That results in two connection beeing opened (one during `new JndiConnection(new InitialLdapContext(env, null), getProviderConfig());` in JndiConnectionFactory and one during one of the bind methods in `context.reconnect(config.getControlProcessor(...));`
Closing the connection only closes one of them and one keeps dangling.

Issue only occurs when calling `Connection.open(BindRequest)`. Calling only `Connection.open()` without a bind request object works fine.

Pls refer also to:
* https://bugs.openjdk.java.net/browse/JDK-8059009
* https://issues.apache.org/jira/browse/DIRSTUDIO-1187

We are willing to help here with coding and testing if you like.

One quick idea to solve this is to restructure the classes slightly so that the `LdapContext.reconnect()` call can be omitted. Should not be a big dal to pass all the env upfront and create the connection when binding.

**Comment by dfish3r** [comment] 2019-07-22 01:14
I'm aware of this, I actually filed the issue you referenced. If this isn't fixed there wont' be anyway to perform a bind on an existing connection with JNDI. That's pretty impactful in terms of the ldaptive API. I could probably work around it in some areas, but many uses of connection pooling would be broken. Hopefully the JDK maintainers will see the impact and fix it.

Until then I've recommended that people switch to the UnboundID provider.

**Comment by floragunncom** [comment] 2019-07-22 10:20
@dfish3r Agreed. That said would be great if you could document this somewhere on http://www.ldaptive.org and/or have a know issues section (or even a warning in the logs when using jndi provider with java >=9). The problem is that the issue is not obvious.

**Comment by dfish3r** [comment] 2019-08-12 05:03
Documentation has been updated. This took a while since I decided to couple it with the v2 documentation updates. Pending the outcome of the JDK issue, I will emit a log warning with a bad combination of JNDI and Java >= 9 on the next v1.2 tag.

**Comment by dfish3r** [comment] 2020-08-12 20:50
Here are the potential solutions for this:

1) Upgrade to ldaptive v2
2) Use version 1.3 which defaults to the UnboundID provider
3) Upgrade to Java 14, which should contain the fix for this bug

**Closed by dfish3r** 2020-08-12 20:50 UTC
